<a href="https://colab.research.google.com/github/beertocode/Resources/blob/master/forprmltest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
#PCA DIMENSIONALITY REDUCTION TRANSFORMATION CODE
from numpy import array
from numpy import mean
from numpy import cov
from numpy.linalg import eig
from numpy.linalg import eigh

#  3×2 matrix
matrix = array([[5, 6, 1], [8, 10,6], [12, 18,12]])
print("original Matrix: ","\n")
print(matrix)

# calculate the mean of each column
Mean_col = mean(matrix.T, axis=1)
print("Mean of each column: ","\n")
print(Mean_col)

# center columns by subtracting column means
Centre_col = matrix - Mean_col
print("After zero centering: ","\n")
print(Centre_col)

# calculate covariance matrix of centered matrix
cov_matrix = cov(Centre_col.T)
print("covariance matrix: ","\n")
print(cov_matrix)

# eigendecomposition of covariance matrix
values, vectors = eig(cov_matrix)
dict={}
n=len(values)
for i in range(n):
  dict[values[i]]=vectors[i]
l=list(dict.items())
l.sort(reverse=True) #sort in reverse order
print('Descending order is:\n',l)


original Matrix:  

[[ 5  6  1]
 [ 8 10  6]
 [12 18 12]]
Mean of each column:  

[ 8.33333333 11.33333333  6.33333333]
After zero centering:  

[[-3.33333333 -5.33333333 -5.33333333]
 [-0.33333333 -1.33333333 -0.33333333]
 [ 3.66666667  6.66666667  5.66666667]]
covariance matrix:  

[[12.33333333 21.33333333 19.33333333]
 [21.33333333 37.33333333 33.33333333]
 [19.33333333 33.33333333 30.33333333]]
Descending order is:
 [(79.66106403010394, array([-0.393176  , -0.88888889,  0.23513651])), (0.3389359698961162, array([-0.61561195,  0.44444444,  0.65076191])), (1.6761347011621186e-15, array([-0.68296014,  0.11111111, -0.72195551]))]


In [31]:
d=len(l) #d is dimention of eigenvector matrix
e=[]
lambdav=[]
for i in range(d):
  lambdav.append(l[i][0])
  e.append(l[i][1])
print("eigenvalues in descending order:\n",lambdav,"\n")
print("eigenvector matrix according to descending ordeer of eigenvalues:\n",e)



eigenvalues in descending order:
 [79.66106403010394, 0.3389359698961162, 1.6761347011621186e-15] 

eigenvector matrix according to descending ordeer of eigenvalues:
 [array([-0.393176  , -0.88888889,  0.23513651]), array([-0.61561195,  0.44444444,  0.65076191]), array([-0.68296014,  0.11111111, -0.72195551])]


In [38]:
#CONSTRUCTING TRANSFORMATION MATRIX
#selecting m higher eigenvalues and finding rho_m
def msum(lambdav,m,sd):
  sm=0  #for sum of top m eigenvalues
  for i in range(m):
    sm=sm+lambdav[i]
  return sm/sd


In [57]:
#sd=sum of all eigenvalues
sd=0  #for sum of all eigenvalues
for i in range(d):
  sd=sd+lambdav[i]
sd
#setting eta threshold
eta=0.9
cnt=0 #no. of vectors in transformation matrix
for i in range(1,d+1):
  if(msum(lambdav,i,sd)>eta):
    cnt+=1;
  else:
    break


In [58]:
#transformation matrix Q
Q=[]
for i in range(cnt):
  Q.append(e[i])
Q

[array([-0.393176  , -0.88888889,  0.23513651]),
 array([-0.61561195,  0.44444444,  0.65076191]),
 array([-0.68296014,  0.11111111, -0.72195551])]